#!/bin/bash
set -e

echo "======================================"
echo "🔧 Fixing JavaScript Importmap"
echo "======================================"
echo ""

cd ~/Code/second-brain-app/second-brain-rails

# Check if importmap file exists and update it
echo "Step 1: Checking importmap configuration..."

cat > config/importmap.rb << 'RUBY'
# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
RUBY

echo "✓ Importmap configured"

# Make sure the application.js is in the right place
echo ""
echo "Step 2: Ensuring application.js is properly set up..."

cat > app/javascript/application.js << 'JS'
// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
import "./controllers"

console.log('🚀 Second Brain JavaScript loaded!');

// Keyboard shortcuts
document.addEventListener('turbo:load', function() {
  console.log('⌨️  Setting up keyboard shortcuts...');
  
  document.addEventListener('keydown', function(e) {
    const activeElement = document.activeElement;
    const isInputField = activeElement.tagName === 'INPUT' || 
                        activeElement.tagName === 'TEXTAREA' || 
                        activeElement.isContentEditable;
    
    // / = Focus search
    if (e.key === '/' && !isInputField) {
      e.preventDefault();
      console.log('🔍 Forward slash pressed');
      const searchInput = document.querySelector('input[name="search"]');
      if (searchInput) {
        searchInput.focus();
        console.log('✓ Search focused!');
      }
    }
    
    // n = New note
    if (e.key === 'n' && !isInputField) {
      e.preventDefault();
      console.log('📝 N pressed');
      const newNoteLink = document.querySelector('a[href*="notes/new"]');
      if (newNoteLink) {
        window.location.href = newNoteLink.href;
      }
    }
    
    // Escape = Clear search
    if (e.key === 'Escape') {
      console.log('🚪 Escape pressed');
      if (activeElement.tagName === 'INPUT' || activeElement.tagName === 'TEXTAREA') {
        activeElement.blur();
      }
      const searchInput = document.querySelector('input[name="search"]');
      if (searchInput && searchInput.value) {
        searchInput.value = '';
        const form = searchInput.closest('form');
        if (form) {
          window.location.href = form.action;
        }
      }
    }
  });
  
  console.log('✓ Keyboard shortcuts active!');
});
JS

echo "✓ application.js created"

# Make sure controllers directory exists
echo ""
echo "Step 3: Ensuring controllers directory..."

mkdir -p app/javascript/controllers

# Create index file for controllers
cat > app/javascript/controllers/index.js << 'JS'
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
JS

# Create application controller
cat > app/javascript/controllers/application.js << 'JS'
import { Application } from "@hotwired/stimulus"

const application = Application.start()

// Configure Stimulus development experience
application.debug = false
window.Stimulus   = application

export { application }
JS

echo "✓ Controllers set up"

# Update the pins
echo ""
echo "Step 4: Updating importmap pins..."

bin/rails importmap:install 2>/dev/null || echo "Importmap already installed"

echo "✓ Importmap updated"

echo ""
echo "======================================"
echo "✅ JavaScript Fixed!"
echo "======================================"
echo ""
echo "Now:"
echo "1. RESTART Rails server (Ctrl+C then bin/rails server)"
echo "2. Hard refresh browser (Ctrl+Shift+R or Cmd+Shift+R)"
echo "3. Check Console (F12) - error should be gone!"
echo "4. Try pressing / to search"
echo ""