#!/bin/bash

echo "======================================"
echo "🧠 Second Brain - Quick Reference"
echo "======================================"
echo ""
echo "TEST USER CREDENTIALS:"
echo "  Email:    test@example.com"
echo "  Password: password123"
echo ""
echo "URLS:"
echo "  App:          http://localhost:3000"
echo "  Notes:        http://localhost:3000/notes"
echo "  Profile:      http://localhost:3000/profile"
echo "  VEPS Status:  http://localhost:3000/veps/status"
echo ""
echo "VEPS API:"
echo "  Endpoint:  https://api-gateway-846963717514.us-east1.run.app"
echo "  API Key:   eecc1ae94876a7b2729643de2b066698f5d9c64388a20917b437afb1862d9941"
echo "  Rate:      1000 requests/minute"
echo ""
echo "KEYBOARD SHORTCUTS:"
echo "  /        Focus search (on notes page)"
echo "  n        New note"
echo "  r        Reading mode (on note page)"
echo "  e        Edit note (on note page)"
echo "  ?        Show help"
echo "  ESC      Clear/unfocus"
echo ""
echo "TO START SERVER:"
echo "  cd ~/Code/second-brain-app/second-brain-rails"
echo "  bin/rails server"
echo ""
echo "TO CREATE NEW USER (if needed):"
echo "  bin/rails console"
echo "  User.create!(email: 'your@email.com', password: 'yourpassword')"
echo ""
echo "USEFUL COMMANDS:"
echo "  bin/rails console              # Open Rails console"
echo "  bin/rails db:migrate          # Run migrations"
echo "  tail -f log/development.log   # Watch logs"
echo ""
echo "PROJECT DIRECTORY:"
echo "  ~/Code/second-brain-app/second-brain-rails"
echo ""
echo "======================================"
